# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.garages_api import GaragesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGaragesApi(unittest.TestCase):
    """GaragesApi unit test stubs"""

    def setUp(self):
        self.api = api.garages_api.GaragesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_garage_id_get(self):
        """Test case for garage_id_get

        Return a garage object with the specified ID.  # noqa: E501
        """
        pass

    def test_garage_id_patch(self):
        """Test case for garage_id_patch

        Allows control of a garage.  # noqa: E501
        """
        pass

    def test_garages_get(self):
        """Test case for garages_get

        Return a list of garages  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
