# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.weather_api import WeatherApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWeatherApi(unittest.TestCase):
    """WeatherApi unit test stubs"""

    def setUp(self):
        self.api = api.weather_api.WeatherApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_weather_alerts_current_get(self):
        """Test case for weather_alerts_current_get

        Return the current weather alert  # noqa: E501
        """
        pass

    def test_weather_alerts_date_get(self):
        """Test case for weather_alerts_date_get

        Return a list of weather alerts from given date  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
