# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.sessions_api import SessionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSessionsApi(unittest.TestCase):
    """SessionsApi unit test stubs"""

    def setUp(self):
        self.api = api.sessions_api.SessionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_session_get(self):
        """Test case for session_get

        Current session information.  # noqa: E501
        """
        pass

    def test_session_post(self):
        """Test case for session_post

        TOKEN TYPE: SCHEDULING. Creates a new USER type token with API access between a specific date and time.  # noqa: E501
        """
        pass

    def test_sessions_get(self):
        """Test case for sessions_get

        TOKEN TYPE: ADMIN. Lists all active sessions across all facilities.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
