# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.signalid_state_left import SignalidStateLeft  # noqa: E501
from swagger_client.rest import ApiException


class TestSignalidStateLeft(unittest.TestCase):
    """SignalidStateLeft unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSignalidStateLeft(self):
        """Test SignalidStateLeft"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.signalid_state_left.SignalidStateLeft()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
