# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.scenarios_api import ScenariosApi  # noqa: E501
from swagger_client.rest import ApiException


class TestScenariosApi(unittest.TestCase):
    """ScenariosApi unit test stubs"""

    def setUp(self):
        self.api = api.scenarios_api.ScenariosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_scenario_id_delete(self):
        """Test case for scenario_id_delete

        Delete a scenario from the database  # noqa: E501
        """
        pass

    def test_scenario_id_get(self):
        """Test case for scenario_id_get

        Return a scenario object with the specified id  # noqa: E501
        """
        pass

    def test_scenario_id_patch(self):
        """Test case for scenario_id_patch

        Update an existing scenario  # noqa: E501
        """
        pass

    def test_scenario_post(self):
        """Test case for scenario_post

        Create a new scenario object  # noqa: E501
        """
        pass

    def test_scenarios_get(self):
        """Test case for scenarios_get

        Return a list of scenario objects.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
