# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.rail_api import RailApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRailApi(unittest.TestCase):
    """RailApi unit test stubs"""

    def setUp(self):
        self.api = api.rail_api.RailApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_railcrossing_id_get(self):
        """Test case for railcrossing_id_get

        Return an rail crossing object with the specified ID.  # noqa: E501
        """
        pass

    def test_railcrossing_id_patch(self):
        """Test case for railcrossing_id_patch

        Updates an existing rail crossing status, allowing for triggering. Returns request ID on success.  # noqa: E501
        """
        pass

    def test_railcrossings_get(self):
        """Test case for railcrossings_get

        Return a list of rail crossing objects describing all instrumented crossings within the facility.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
