# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.body12 import Body12  # noqa: E501
from swagger_client.rest import ApiException


class TestBody12(unittest.TestCase):
    """Body12 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody12(self):
        """Test Body12"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.body12.Body12()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
