# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.intersections_api import IntersectionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIntersectionsApi(unittest.TestCase):
    """IntersectionsApi unit test stubs"""

    def setUp(self):
        self.api = api.intersections_api.IntersectionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_intersection_id_crosswalks_get(self):
        """Test case for intersection_id_crosswalks_get

        Return list of crosswalks within an intersection  # noqa: E501
        """
        pass

    def test_intersection_id_get(self):
        """Test case for intersection_id_get

        Return an intersection object with the specified ID.  # noqa: E501
        """
        pass

    def test_intersection_id_patch(self):
        """Test case for intersection_id_patch

        Allows control one to many phases within an intersection.  # noqa: E501
        """
        pass

    def test_intersection_id_phases_get(self):
        """Test case for intersection_id_phases_get

        Return list of phases configured for an intersection  # noqa: E501
        """
        pass

    def test_intersection_id_preempt_preempt_id_patch(self):
        """Test case for intersection_id_preempt_preempt_id_patch

        Allows enabling/disabling preconfigured preempt at an intersection.  # noqa: E501
        """
        pass

    def test_intersection_id_signals_get(self):
        """Test case for intersection_id_signals_get

        Return list of traffic signal configured for an intersection  # noqa: E501
        """
        pass

    def test_intersection_id_stages_get(self):
        """Test case for intersection_id_stages_get

        Return list of suggested control groupings for the intersection (stages)  # noqa: E501
        """
        pass

    def test_intersections_get(self):
        """Test case for intersections_get

        Return a list of intersection objects.  # noqa: E501
        """
        pass

    def test_intersections_patch(self):
        """Test case for intersections_patch

        Sets features on all configured intersections that support a feature.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
