# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.api_error import APIError  # noqa: E501
from swagger_client.rest import ApiException


class TestAPIError(unittest.TestCase):
    """APIError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAPIError(self):
        """Test APIError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_error.APIError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
