# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.management_api import ManagementApi  # noqa: E501
from swagger_client.rest import ApiException


class TestManagementApi(unittest.TestCase):
    """ManagementApi unit test stubs"""

    def setUp(self):
        self.api = api.management_api.ManagementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_management_device_callback_post(self):
        """Test case for management_device_callback_post

        TOKEN TYPE: DEVICE. Handles callbacks from physical devices connected to API.  # noqa: E501
        """
        pass

    def test_management_facility_reset_post(self):
        """Test case for management_facility_reset_post

        TOKEN TYPE: USER. Reset controllable items within the facility.  # noqa: E501
        """
        pass

    def test_management_favorite_module_name_favorite_id_delete(self):
        """Test case for management_favorite_module_name_favorite_id_delete

        Delete a favorite from the database.  # noqa: E501
        """
        pass

    def test_management_favorite_post(self):
        """Test case for management_favorite_post

        Add a favorite to database.  # noqa: E501
        """
        pass

    def test_management_favorites_get(self):
        """Test case for management_favorites_get

        Retrieve list of all favorites.  # noqa: E501
        """
        pass

    def test_management_modules_get(self):
        """Test case for management_modules_get

        Return a list of Modules supported by this instance of Octane  # noqa: E501
        """
        pass

    def test_management_polling_intersections_patch(self):
        """Test case for management_polling_intersections_patch

        TOKEN TYPE: ADMIN. Start/Stop Intersection Traffic signal polling.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
