# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Body40(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'x_api_key': 'str'
    }

    attribute_map = {
        'x_api_key': 'x-api-key'
    }

    def __init__(self, x_api_key=None):  # noqa: E501
        """Body40 - a model defined in Swagger"""  # noqa: E501
        self._x_api_key = None
        self.discriminator = None
        if x_api_key is not None:
            self.x_api_key = x_api_key

    @property
    def x_api_key(self):
        """Gets the x_api_key of this Body40.  # noqa: E501

        The authentication token to login to the socket feed with.  # noqa: E501

        :return: The x_api_key of this Body40.  # noqa: E501
        :rtype: str
        """
        return self._x_api_key

    @x_api_key.setter
    def x_api_key(self, x_api_key):
        """Sets the x_api_key of this Body40.

        The authentication token to login to the socket feed with.  # noqa: E501

        :param x_api_key: The x_api_key of this Body40.  # noqa: E501
        :type: str
        """

        self._x_api_key = x_api_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body40, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body40):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
