# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Body35(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data': 'str',
        'event': 'str',
        'coreid': 'str',
        'published_at': 'str'
    }

    attribute_map = {
        'data': 'data',
        'event': 'event',
        'coreid': 'coreid',
        'published_at': 'published_at'
    }

    def __init__(self, data=None, event=None, coreid=None, published_at=None):  # noqa: E501
        """Body35 - a model defined in Swagger"""  # noqa: E501
        self._data = None
        self._event = None
        self._coreid = None
        self._published_at = None
        self.discriminator = None
        if data is not None:
            self.data = data
        if event is not None:
            self.event = event
        if coreid is not None:
            self.coreid = coreid
        if published_at is not None:
            self.published_at = published_at

    @property
    def data(self):
        """Gets the data of this Body35.  # noqa: E501

        Data from event  # noqa: E501

        :return: The data of this Body35.  # noqa: E501
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this Body35.

        Data from event  # noqa: E501

        :param data: The data of this Body35.  # noqa: E501
        :type: str
        """

        self._data = data

    @property
    def event(self):
        """Gets the event of this Body35.  # noqa: E501

        Remote Event name  # noqa: E501

        :return: The event of this Body35.  # noqa: E501
        :rtype: str
        """
        return self._event

    @event.setter
    def event(self, event):
        """Sets the event of this Body35.

        Remote Event name  # noqa: E501

        :param event: The event of this Body35.  # noqa: E501
        :type: str
        """

        self._event = event

    @property
    def coreid(self):
        """Gets the coreid of this Body35.  # noqa: E501

        Device ID of calling device  # noqa: E501

        :return: The coreid of this Body35.  # noqa: E501
        :rtype: str
        """
        return self._coreid

    @coreid.setter
    def coreid(self, coreid):
        """Sets the coreid of this Body35.

        Device ID of calling device  # noqa: E501

        :param coreid: The coreid of this Body35.  # noqa: E501
        :type: str
        """

        self._coreid = coreid

    @property
    def published_at(self):
        """Gets the published_at of this Body35.  # noqa: E501

        The time this event was published.  # noqa: E501

        :return: The published_at of this Body35.  # noqa: E501
        :rtype: str
        """
        return self._published_at

    @published_at.setter
    def published_at(self, published_at):
        """Sets the published_at of this Body35.

        The time this event was published.  # noqa: E501

        :param published_at: The published_at of this Body35.  # noqa: E501
        :type: str
        """

        self._published_at = published_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body35, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body35):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
