# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Body32(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'module_name': 'str',
        'favorite_id': 'int'
    }

    attribute_map = {
        'module_name': 'moduleName',
        'favorite_id': 'favoriteID'
    }

    def __init__(self, module_name=None, favorite_id=None):  # noqa: E501
        """Body32 - a model defined in Swagger"""  # noqa: E501
        self._module_name = None
        self._favorite_id = None
        self.discriminator = None
        if module_name is not None:
            self.module_name = module_name
        if favorite_id is not None:
            self.favorite_id = favorite_id

    @property
    def module_name(self):
        """Gets the module_name of this Body32.  # noqa: E501


        :return: The module_name of this Body32.  # noqa: E501
        :rtype: str
        """
        return self._module_name

    @module_name.setter
    def module_name(self, module_name):
        """Sets the module_name of this Body32.


        :param module_name: The module_name of this Body32.  # noqa: E501
        :type: str
        """

        self._module_name = module_name

    @property
    def favorite_id(self):
        """Gets the favorite_id of this Body32.  # noqa: E501


        :return: The favorite_id of this Body32.  # noqa: E501
        :rtype: int
        """
        return self._favorite_id

    @favorite_id.setter
    def favorite_id(self, favorite_id):
        """Sets the favorite_id of this Body32.


        :param favorite_id: The favorite_id of this Body32.  # noqa: E501
        :type: int
        """

        self._favorite_id = favorite_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body32, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body32):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
