# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class InlineResponse20047(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'v2xs': 'list[V2X]'
    }

    attribute_map = {
        'v2xs': 'v2xs'
    }

    def __init__(self, v2xs=None):  # noqa: E501
        """InlineResponse20047 - a model defined in Swagger"""  # noqa: E501
        self._v2xs = None
        self.discriminator = None
        if v2xs is not None:
            self.v2xs = v2xs

    @property
    def v2xs(self):
        """Gets the v2xs of this InlineResponse20047.  # noqa: E501

        A list of V2X devices.  # noqa: E501

        :return: The v2xs of this InlineResponse20047.  # noqa: E501
        :rtype: list[V2X]
        """
        return self._v2xs

    @v2xs.setter
    def v2xs(self, v2xs):
        """Sets the v2xs of this InlineResponse20047.

        A list of V2X devices.  # noqa: E501

        :param v2xs: The v2xs of this InlineResponse20047.  # noqa: E501
        :type: list[V2X]
        """

        self._v2xs = v2xs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20047, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20047):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
