# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class IPCMessage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'payload': 'str',
        'type': 'str',
        'time': 'datetime'
    }

    attribute_map = {
        'payload': 'payload',
        'type': 'type',
        'time': 'time'
    }

    def __init__(self, payload=None, type=None, time=None):  # noqa: E501
        """IPCMessage - a model defined in Swagger"""  # noqa: E501
        self._payload = None
        self._type = None
        self._time = None
        self.discriminator = None
        if payload is not None:
            self.payload = payload
        if type is not None:
            self.type = type
        if time is not None:
            self.time = time

    @property
    def payload(self):
        """Gets the payload of this IPCMessage.  # noqa: E501

        A message payload object to be shared related to the listed type.  # noqa: E501

        :return: The payload of this IPCMessage.  # noqa: E501
        :rtype: str
        """
        return self._payload

    @payload.setter
    def payload(self, payload):
        """Sets the payload of this IPCMessage.

        A message payload object to be shared related to the listed type.  # noqa: E501

        :param payload: The payload of this IPCMessage.  # noqa: E501
        :type: str
        """

        self._payload = payload

    @property
    def type(self):
        """Gets the type of this IPCMessage.  # noqa: E501

        A string representing the type of IPC message. Reserved IPC types are shown below. Contact mcity-engineering@umich.edu to request a reserved type.  # noqa: E501

        :return: The type of this IPCMessage.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this IPCMessage.

        A string representing the type of IPC message. Reserved IPC types are shown below. Contact mcity-engineering@umich.edu to request a reserved type.  # noqa: E501

        :param type: The type of this IPCMessage.  # noqa: E501
        :type: str
        """
        allowed_values = ["POI", "OVERLAY", "SCENARIO"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def time(self):
        """Gets the time of this IPCMessage.  # noqa: E501

        Time that the message was sent to the server. This is server generated.  # noqa: E501

        :return: The time of this IPCMessage.  # noqa: E501
        :rtype: datetime
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this IPCMessage.

        Time that the message was sent to the server. This is server generated.  # noqa: E501

        :param time: The time of this IPCMessage.  # noqa: E501
        :type: datetime
        """

        self._time = time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IPCMessage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IPCMessage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
