# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class RailcrossingidState(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'manual_call': 'bool',
        'manual_call_time_override': 'int',
        'activated': 'bool'
    }

    attribute_map = {
        'manual_call': 'manualCall',
        'manual_call_time_override': 'manualCallTimeOverride',
        'activated': 'activated'
    }

    def __init__(self, manual_call=None, manual_call_time_override=None, activated=None):  # noqa: E501
        """RailcrossingidState - a model defined in Swagger"""  # noqa: E501
        self._manual_call = None
        self._manual_call_time_override = None
        self._activated = None
        self.discriminator = None
        if manual_call is not None:
            self.manual_call = manual_call
        if manual_call_time_override is not None:
            self.manual_call_time_override = manual_call_time_override
        if activated is not None:
            self.activated = activated

    @property
    def manual_call(self):
        """Gets the manual_call of this RailcrossingidState.  # noqa: E501

        Activate rail crossing cycle (close, wait, open)  # noqa: E501

        :return: The manual_call of this RailcrossingidState.  # noqa: E501
        :rtype: bool
        """
        return self._manual_call

    @manual_call.setter
    def manual_call(self, manual_call):
        """Sets the manual_call of this RailcrossingidState.

        Activate rail crossing cycle (close, wait, open)  # noqa: E501

        :param manual_call: The manual_call of this RailcrossingidState.  # noqa: E501
        :type: bool
        """

        self._manual_call = manual_call

    @property
    def manual_call_time_override(self):
        """Gets the manual_call_time_override of this RailcrossingidState.  # noqa: E501

        Specify a length of time the gate should stay in the closed position during a manual call. This setting does not persist.  # noqa: E501

        :return: The manual_call_time_override of this RailcrossingidState.  # noqa: E501
        :rtype: int
        """
        return self._manual_call_time_override

    @manual_call_time_override.setter
    def manual_call_time_override(self, manual_call_time_override):
        """Sets the manual_call_time_override of this RailcrossingidState.

        Specify a length of time the gate should stay in the closed position during a manual call. This setting does not persist.  # noqa: E501

        :param manual_call_time_override: The manual_call_time_override of this RailcrossingidState.  # noqa: E501
        :type: int
        """

        self._manual_call_time_override = manual_call_time_override

    @property
    def activated(self):
        """Gets the activated of this RailcrossingidState.  # noqa: E501

        Activate or deactivate the rail crossing.  # noqa: E501

        :return: The activated of this RailcrossingidState.  # noqa: E501
        :rtype: bool
        """
        return self._activated

    @activated.setter
    def activated(self, activated):
        """Sets the activated of this RailcrossingidState.

        Activate or deactivate the rail crossing.  # noqa: E501

        :param activated: The activated of this RailcrossingidState.  # noqa: E501
        :type: bool
        """

        self._activated = activated

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RailcrossingidState, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RailcrossingidState):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
