# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class SafetyEquipment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'unit_id': 'str',
        'name': 'str'
    }

    attribute_map = {
        'id': 'id',
        'unit_id': 'unitID',
        'name': 'name'
    }

    def __init__(self, id=None, unit_id=None, name=None):  # noqa: E501
        """SafetyEquipment - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._unit_id = None
        self._name = None
        self.discriminator = None
        self.id = id
        self.unit_id = unit_id
        if name is not None:
            self.name = name

    @property
    def id(self):
        """Gets the id of this SafetyEquipment.  # noqa: E501

        An ID number identifying this piece of safety equipment  # noqa: E501

        :return: The id of this SafetyEquipment.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SafetyEquipment.

        An ID number identifying this piece of safety equipment  # noqa: E501

        :param id: The id of this SafetyEquipment.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def unit_id(self):
        """Gets the unit_id of this SafetyEquipment.  # noqa: E501

        The unit ID that the safety equipment responds with.  # noqa: E501

        :return: The unit_id of this SafetyEquipment.  # noqa: E501
        :rtype: str
        """
        return self._unit_id

    @unit_id.setter
    def unit_id(self, unit_id):
        """Sets the unit_id of this SafetyEquipment.

        The unit ID that the safety equipment responds with.  # noqa: E501

        :param unit_id: The unit_id of this SafetyEquipment.  # noqa: E501
        :type: str
        """
        if unit_id is None:
            raise ValueError("Invalid value for `unit_id`, must not be `None`")  # noqa: E501

        self._unit_id = unit_id

    @property
    def name(self):
        """Gets the name of this SafetyEquipment.  # noqa: E501

        A text based description of the safety equipment.  # noqa: E501

        :return: The name of this SafetyEquipment.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SafetyEquipment.

        A text based description of the safety equipment.  # noqa: E501

        :param name: The name of this SafetyEquipment.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SafetyEquipment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SafetyEquipment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
