# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Scenario(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'owner': 'str',
        'workspace': 'str',
        'last_modified': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'owner': 'owner',
        'workspace': 'workspace',
        'last_modified': 'lastModified'
    }

    def __init__(self, id=None, name=None, owner=None, workspace=None, last_modified=None):  # noqa: E501
        """Scenario - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._owner = None
        self._workspace = None
        self._last_modified = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if owner is not None:
            self.owner = owner
        if workspace is not None:
            self.workspace = workspace
        if last_modified is not None:
            self.last_modified = last_modified

    @property
    def id(self):
        """Gets the id of this Scenario.  # noqa: E501

        ID of the scenario  # noqa: E501

        :return: The id of this Scenario.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Scenario.

        ID of the scenario  # noqa: E501

        :param id: The id of this Scenario.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Scenario.  # noqa: E501

        Name of the scenario  # noqa: E501

        :return: The name of this Scenario.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Scenario.

        Name of the scenario  # noqa: E501

        :param name: The name of this Scenario.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def owner(self):
        """Gets the owner of this Scenario.  # noqa: E501

        Email of the scenario owner  # noqa: E501

        :return: The owner of this Scenario.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this Scenario.

        Email of the scenario owner  # noqa: E501

        :param owner: The owner of this Scenario.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def workspace(self):
        """Gets the workspace of this Scenario.  # noqa: E501

        The XML structure containing the code to be run in the scenario  # noqa: E501

        :return: The workspace of this Scenario.  # noqa: E501
        :rtype: str
        """
        return self._workspace

    @workspace.setter
    def workspace(self, workspace):
        """Sets the workspace of this Scenario.

        The XML structure containing the code to be run in the scenario  # noqa: E501

        :param workspace: The workspace of this Scenario.  # noqa: E501
        :type: str
        """

        self._workspace = workspace

    @property
    def last_modified(self):
        """Gets the last_modified of this Scenario.  # noqa: E501

        Time that the scenario was last modified  # noqa: E501

        :return: The last_modified of this Scenario.  # noqa: E501
        :rtype: datetime
        """
        return self._last_modified

    @last_modified.setter
    def last_modified(self, last_modified):
        """Sets the last_modified of this Scenario.

        Time that the scenario was last modified  # noqa: E501

        :param last_modified: The last_modified of this Scenario.  # noqa: E501
        :type: datetime
        """

        self._last_modified = last_modified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Scenario, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Scenario):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
