# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class SensorState(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'enabled': 'bool',
        'updated': 'datetime'
    }

    attribute_map = {
        'enabled': 'enabled',
        'updated': 'updated'
    }

    def __init__(self, enabled=None, updated=None):  # noqa: E501
        """SensorState - a model defined in Swagger"""  # noqa: E501
        self._enabled = None
        self._updated = None
        self.discriminator = None
        if enabled is not None:
            self.enabled = enabled
        if updated is not None:
            self.updated = updated

    @property
    def enabled(self):
        """Gets the enabled of this SensorState.  # noqa: E501

        True / False representing if the sensor presently powered on.  # noqa: E501

        :return: The enabled of this SensorState.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this SensorState.

        True / False representing if the sensor presently powered on.  # noqa: E501

        :param enabled: The enabled of this SensorState.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def updated(self):
        """Gets the updated of this SensorState.  # noqa: E501

        The last time the state of the sensor was updated.  # noqa: E501

        :return: The updated of this SensorState.  # noqa: E501
        :rtype: datetime
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this SensorState.

        The last time the state of the sensor was updated.  # noqa: E501

        :param updated: The updated of this SensorState.  # noqa: E501
        :type: datetime
        """

        self._updated = updated

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SensorState, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SensorState):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
