# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class SensorCamera(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'uri': 'str',
        'name': 'str',
        'url': 'str',
        'longitude': 'float',
        'latitude': 'float',
        'type': 'str',
        'manufacturer': 'str',
        'model': 'str',
        'revision': 'str',
        'ip_address': 'str',
        'url_web_interface': 'str',
        'url_stream': 'str',
        'url_still': 'str',
        'url_stream_format': 'str',
        'url_still_format': 'str',
        'resolution_stream': 'str',
        'resolution_still': 'str',
        'framerate': 'float',
        'lens': 'str',
        'state': 'SensorState'
    }

    attribute_map = {
        'id': 'id',
        'uri': 'uri',
        'name': 'name',
        'url': 'url',
        'longitude': 'longitude',
        'latitude': 'latitude',
        'type': 'type',
        'manufacturer': 'manufacturer',
        'model': 'model',
        'revision': 'revision',
        'ip_address': 'ipAddress',
        'url_web_interface': 'urlWebInterface',
        'url_stream': 'urlStream',
        'url_still': 'urlStill',
        'url_stream_format': 'urlStreamFormat',
        'url_still_format': 'urlStillFormat',
        'resolution_stream': 'resolutionStream',
        'resolution_still': 'resolutionStill',
        'framerate': 'framerate',
        'lens': 'lens',
        'state': 'state'
    }

    def __init__(self, id=None, uri=None, name=None, url=None, longitude=None, latitude=None, type=None, manufacturer=None, model=None, revision=None, ip_address=None, url_web_interface=None, url_stream=None, url_still=None, url_stream_format=None, url_still_format=None, resolution_stream=None, resolution_still=None, framerate=None, lens=None, state=None):  # noqa: E501
        """SensorCamera - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._uri = None
        self._name = None
        self._url = None
        self._longitude = None
        self._latitude = None
        self._type = None
        self._manufacturer = None
        self._model = None
        self._revision = None
        self._ip_address = None
        self._url_web_interface = None
        self._url_stream = None
        self._url_still = None
        self._url_stream_format = None
        self._url_still_format = None
        self._resolution_stream = None
        self._resolution_still = None
        self._framerate = None
        self._lens = None
        self._state = None
        self.discriminator = None
        self.id = id
        if uri is not None:
            self.uri = uri
        if name is not None:
            self.name = name
        if url is not None:
            self.url = url
        if longitude is not None:
            self.longitude = longitude
        if latitude is not None:
            self.latitude = latitude
        if type is not None:
            self.type = type
        if manufacturer is not None:
            self.manufacturer = manufacturer
        if model is not None:
            self.model = model
        if revision is not None:
            self.revision = revision
        if ip_address is not None:
            self.ip_address = ip_address
        if url_web_interface is not None:
            self.url_web_interface = url_web_interface
        if url_stream is not None:
            self.url_stream = url_stream
        if url_still is not None:
            self.url_still = url_still
        if url_stream_format is not None:
            self.url_stream_format = url_stream_format
        if url_still_format is not None:
            self.url_still_format = url_still_format
        if resolution_stream is not None:
            self.resolution_stream = resolution_stream
        if resolution_still is not None:
            self.resolution_still = resolution_still
        if framerate is not None:
            self.framerate = framerate
        if lens is not None:
            self.lens = lens
        if state is not None:
            self.state = state

    @property
    def id(self):
        """Gets the id of this SensorCamera.  # noqa: E501

        An ID number identifying this sensor  # noqa: E501

        :return: The id of this SensorCamera.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SensorCamera.

        An ID number identifying this sensor  # noqa: E501

        :param id: The id of this SensorCamera.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def uri(self):
        """Gets the uri of this SensorCamera.  # noqa: E501

        The URI which can be used to access this sensor  # noqa: E501

        :return: The uri of this SensorCamera.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this SensorCamera.

        The URI which can be used to access this sensor  # noqa: E501

        :param uri: The uri of this SensorCamera.  # noqa: E501
        :type: str
        """

        self._uri = uri

    @property
    def name(self):
        """Gets the name of this SensorCamera.  # noqa: E501

        A text based description of the sensor  # noqa: E501

        :return: The name of this SensorCamera.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SensorCamera.

        A text based description of the sensor  # noqa: E501

        :param name: The name of this SensorCamera.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def url(self):
        """Gets the url of this SensorCamera.  # noqa: E501

        A url with more information about this specific sensor  # noqa: E501

        :return: The url of this SensorCamera.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this SensorCamera.

        A url with more information about this specific sensor  # noqa: E501

        :param url: The url of this SensorCamera.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def longitude(self):
        """Gets the longitude of this SensorCamera.  # noqa: E501

        The longitude of the centroid of the sensor  # noqa: E501

        :return: The longitude of this SensorCamera.  # noqa: E501
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this SensorCamera.

        The longitude of the centroid of the sensor  # noqa: E501

        :param longitude: The longitude of this SensorCamera.  # noqa: E501
        :type: float
        """

        self._longitude = longitude

    @property
    def latitude(self):
        """Gets the latitude of this SensorCamera.  # noqa: E501

        The latitude of the centroid of the sensor  # noqa: E501

        :return: The latitude of this SensorCamera.  # noqa: E501
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this SensorCamera.

        The latitude of the centroid of the sensor  # noqa: E501

        :param latitude: The latitude of this SensorCamera.  # noqa: E501
        :type: float
        """

        self._latitude = latitude

    @property
    def type(self):
        """Gets the type of this SensorCamera.  # noqa: E501

        The sensor type  # noqa: E501

        :return: The type of this SensorCamera.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this SensorCamera.

        The sensor type  # noqa: E501

        :param type: The type of this SensorCamera.  # noqa: E501
        :type: str
        """
        allowed_values = ["Camera"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def manufacturer(self):
        """Gets the manufacturer of this SensorCamera.  # noqa: E501

        The sensor manufacturer  # noqa: E501

        :return: The manufacturer of this SensorCamera.  # noqa: E501
        :rtype: str
        """
        return self._manufacturer

    @manufacturer.setter
    def manufacturer(self, manufacturer):
        """Sets the manufacturer of this SensorCamera.

        The sensor manufacturer  # noqa: E501

        :param manufacturer: The manufacturer of this SensorCamera.  # noqa: E501
        :type: str
        """

        self._manufacturer = manufacturer

    @property
    def model(self):
        """Gets the model of this SensorCamera.  # noqa: E501

        The model number/name of the sensor  # noqa: E501

        :return: The model of this SensorCamera.  # noqa: E501
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this SensorCamera.

        The model number/name of the sensor  # noqa: E501

        :param model: The model of this SensorCamera.  # noqa: E501
        :type: str
        """

        self._model = model

    @property
    def revision(self):
        """Gets the revision of this SensorCamera.  # noqa: E501

        Sensor revision number/edition information  # noqa: E501

        :return: The revision of this SensorCamera.  # noqa: E501
        :rtype: str
        """
        return self._revision

    @revision.setter
    def revision(self, revision):
        """Sets the revision of this SensorCamera.

        Sensor revision number/edition information  # noqa: E501

        :param revision: The revision of this SensorCamera.  # noqa: E501
        :type: str
        """

        self._revision = revision

    @property
    def ip_address(self):
        """Gets the ip_address of this SensorCamera.  # noqa: E501

        The IP Address of the sensor  # noqa: E501

        :return: The ip_address of this SensorCamera.  # noqa: E501
        :rtype: str
        """
        return self._ip_address

    @ip_address.setter
    def ip_address(self, ip_address):
        """Sets the ip_address of this SensorCamera.

        The IP Address of the sensor  # noqa: E501

        :param ip_address: The ip_address of this SensorCamera.  # noqa: E501
        :type: str
        """

        self._ip_address = ip_address

    @property
    def url_web_interface(self):
        """Gets the url_web_interface of this SensorCamera.  # noqa: E501

        A URL allowing control or management of the sensor  # noqa: E501

        :return: The url_web_interface of this SensorCamera.  # noqa: E501
        :rtype: str
        """
        return self._url_web_interface

    @url_web_interface.setter
    def url_web_interface(self, url_web_interface):
        """Sets the url_web_interface of this SensorCamera.

        A URL allowing control or management of the sensor  # noqa: E501

        :param url_web_interface: The url_web_interface of this SensorCamera.  # noqa: E501
        :type: str
        """

        self._url_web_interface = url_web_interface

    @property
    def url_stream(self):
        """Gets the url_stream of this SensorCamera.  # noqa: E501

        A URL for retrieving a stream of video from the camera.  # noqa: E501

        :return: The url_stream of this SensorCamera.  # noqa: E501
        :rtype: str
        """
        return self._url_stream

    @url_stream.setter
    def url_stream(self, url_stream):
        """Sets the url_stream of this SensorCamera.

        A URL for retrieving a stream of video from the camera.  # noqa: E501

        :param url_stream: The url_stream of this SensorCamera.  # noqa: E501
        :type: str
        """

        self._url_stream = url_stream

    @property
    def url_still(self):
        """Gets the url_still of this SensorCamera.  # noqa: E501

        A URL allowing still capture from the camera.  # noqa: E501

        :return: The url_still of this SensorCamera.  # noqa: E501
        :rtype: str
        """
        return self._url_still

    @url_still.setter
    def url_still(self, url_still):
        """Sets the url_still of this SensorCamera.

        A URL allowing still capture from the camera.  # noqa: E501

        :param url_still: The url_still of this SensorCamera.  # noqa: E501
        :type: str
        """

        self._url_still = url_still

    @property
    def url_stream_format(self):
        """Gets the url_stream_format of this SensorCamera.  # noqa: E501

        The file format of the stream endpoint.  # noqa: E501

        :return: The url_stream_format of this SensorCamera.  # noqa: E501
        :rtype: str
        """
        return self._url_stream_format

    @url_stream_format.setter
    def url_stream_format(self, url_stream_format):
        """Sets the url_stream_format of this SensorCamera.

        The file format of the stream endpoint.  # noqa: E501

        :param url_stream_format: The url_stream_format of this SensorCamera.  # noqa: E501
        :type: str
        """

        self._url_stream_format = url_stream_format

    @property
    def url_still_format(self):
        """Gets the url_still_format of this SensorCamera.  # noqa: E501

        The file format of the still endpoint.  # noqa: E501

        :return: The url_still_format of this SensorCamera.  # noqa: E501
        :rtype: str
        """
        return self._url_still_format

    @url_still_format.setter
    def url_still_format(self, url_still_format):
        """Sets the url_still_format of this SensorCamera.

        The file format of the still endpoint.  # noqa: E501

        :param url_still_format: The url_still_format of this SensorCamera.  # noqa: E501
        :type: str
        """

        self._url_still_format = url_still_format

    @property
    def resolution_stream(self):
        """Gets the resolution_stream of this SensorCamera.  # noqa: E501

        The maximum resolution of streaming video.  # noqa: E501

        :return: The resolution_stream of this SensorCamera.  # noqa: E501
        :rtype: str
        """
        return self._resolution_stream

    @resolution_stream.setter
    def resolution_stream(self, resolution_stream):
        """Sets the resolution_stream of this SensorCamera.

        The maximum resolution of streaming video.  # noqa: E501

        :param resolution_stream: The resolution_stream of this SensorCamera.  # noqa: E501
        :type: str
        """

        self._resolution_stream = resolution_stream

    @property
    def resolution_still(self):
        """Gets the resolution_still of this SensorCamera.  # noqa: E501

        The maximum resolution of still capture  # noqa: E501

        :return: The resolution_still of this SensorCamera.  # noqa: E501
        :rtype: str
        """
        return self._resolution_still

    @resolution_still.setter
    def resolution_still(self, resolution_still):
        """Sets the resolution_still of this SensorCamera.

        The maximum resolution of still capture  # noqa: E501

        :param resolution_still: The resolution_still of this SensorCamera.  # noqa: E501
        :type: str
        """

        self._resolution_still = resolution_still

    @property
    def framerate(self):
        """Gets the framerate of this SensorCamera.  # noqa: E501

        The max number of frames achievable at max resolution.  # noqa: E501

        :return: The framerate of this SensorCamera.  # noqa: E501
        :rtype: float
        """
        return self._framerate

    @framerate.setter
    def framerate(self, framerate):
        """Sets the framerate of this SensorCamera.

        The max number of frames achievable at max resolution.  # noqa: E501

        :param framerate: The framerate of this SensorCamera.  # noqa: E501
        :type: float
        """

        self._framerate = framerate

    @property
    def lens(self):
        """Gets the lens of this SensorCamera.  # noqa: E501

        Detail about camera lens information.  # noqa: E501

        :return: The lens of this SensorCamera.  # noqa: E501
        :rtype: str
        """
        return self._lens

    @lens.setter
    def lens(self, lens):
        """Sets the lens of this SensorCamera.

        Detail about camera lens information.  # noqa: E501

        :param lens: The lens of this SensorCamera.  # noqa: E501
        :type: str
        """

        self._lens = lens

    @property
    def state(self):
        """Gets the state of this SensorCamera.  # noqa: E501


        :return: The state of this SensorCamera.  # noqa: E501
        :rtype: SensorState
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this SensorCamera.


        :param state: The state of this SensorCamera.  # noqa: E501
        :type: SensorState
        """

        self._state = state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SensorCamera, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SensorCamera):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
