# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class UserMessage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'message': 'str',
        'user': 'str',
        'time': 'datetime'
    }

    attribute_map = {
        'message': 'message',
        'user': 'user',
        'time': 'time'
    }

    def __init__(self, message=None, user=None, time=None):  # noqa: E501
        """UserMessage - a model defined in Swagger"""  # noqa: E501
        self._message = None
        self._user = None
        self._time = None
        self.discriminator = None
        if message is not None:
            self.message = message
        if user is not None:
            self.user = user
        if time is not None:
            self.time = time

    @property
    def message(self):
        """Gets the message of this UserMessage.  # noqa: E501

        A message  # noqa: E501

        :return: The message of this UserMessage.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this UserMessage.

        A message  # noqa: E501

        :param message: The message of this UserMessage.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def user(self):
        """Gets the user of this UserMessage.  # noqa: E501

        The user name provided as the message sender.  # noqa: E501

        :return: The user of this UserMessage.  # noqa: E501
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this UserMessage.

        The user name provided as the message sender.  # noqa: E501

        :param user: The user of this UserMessage.  # noqa: E501
        :type: str
        """

        self._user = user

    @property
    def time(self):
        """Gets the time of this UserMessage.  # noqa: E501

        Time that the message was sent.  # noqa: E501

        :return: The time of this UserMessage.  # noqa: E501
        :rtype: datetime
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this UserMessage.

        Time that the message was sent.  # noqa: E501

        :param time: The time of this UserMessage.  # noqa: E501
        :type: datetime
        """

        self._time = time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserMessage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserMessage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
