# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class V2XBSM(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'id_temporary': 'str',
        'id_fixed': 'str',
        'message_set': 'str',
        'vehicle_length': 'float',
        'vehicle_width': 'float',
        'updated': 'datetime',
        'longitude': 'float',
        'latitude': 'float',
        'elevation': 'float',
        'speed': 'float',
        'heading': 'float',
        'angle': 'float'
    }

    attribute_map = {
        'id': 'id',
        'id_temporary': 'idTemporary',
        'id_fixed': 'idFixed',
        'message_set': 'messageSet',
        'vehicle_length': 'vehicleLength',
        'vehicle_width': 'vehicleWidth',
        'updated': 'updated',
        'longitude': 'longitude',
        'latitude': 'latitude',
        'elevation': 'elevation',
        'speed': 'speed',
        'heading': 'heading',
        'angle': 'angle'
    }

    def __init__(self, id=None, id_temporary=None, id_fixed=None, message_set=None, vehicle_length=None, vehicle_width=None, updated=None, longitude=None, latitude=None, elevation=None, speed=None, heading=None, angle=None):  # noqa: E501
        """V2XBSM - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._id_temporary = None
        self._id_fixed = None
        self._message_set = None
        self._vehicle_length = None
        self._vehicle_width = None
        self._updated = None
        self._longitude = None
        self._latitude = None
        self._elevation = None
        self._speed = None
        self._heading = None
        self._angle = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if id_temporary is not None:
            self.id_temporary = id_temporary
        if id_fixed is not None:
            self.id_fixed = id_fixed
        if message_set is not None:
            self.message_set = message_set
        if vehicle_length is not None:
            self.vehicle_length = vehicle_length
        if vehicle_width is not None:
            self.vehicle_width = vehicle_width
        if updated is not None:
            self.updated = updated
        if longitude is not None:
            self.longitude = longitude
        if latitude is not None:
            self.latitude = latitude
        if elevation is not None:
            self.elevation = elevation
        if speed is not None:
            self.speed = speed
        if heading is not None:
            self.heading = heading
        if angle is not None:
            self.angle = angle

    @property
    def id(self):
        """Gets the id of this V2XBSM.  # noqa: E501

        Static identifier if available, else temporary identifier provided by OBU.  # noqa: E501

        :return: The id of this V2XBSM.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this V2XBSM.

        Static identifier if available, else temporary identifier provided by OBU.  # noqa: E501

        :param id: The id of this V2XBSM.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def id_temporary(self):
        """Gets the id_temporary of this V2XBSM.  # noqa: E501

        Temporary identifier  # noqa: E501

        :return: The id_temporary of this V2XBSM.  # noqa: E501
        :rtype: str
        """
        return self._id_temporary

    @id_temporary.setter
    def id_temporary(self, id_temporary):
        """Sets the id_temporary of this V2XBSM.

        Temporary identifier  # noqa: E501

        :param id_temporary: The id_temporary of this V2XBSM.  # noqa: E501
        :type: str
        """

        self._id_temporary = id_temporary

    @property
    def id_fixed(self):
        """Gets the id_fixed of this V2XBSM.  # noqa: E501

        Permanent vehicle identifier for known vehicles.  # noqa: E501

        :return: The id_fixed of this V2XBSM.  # noqa: E501
        :rtype: str
        """
        return self._id_fixed

    @id_fixed.setter
    def id_fixed(self, id_fixed):
        """Sets the id_fixed of this V2XBSM.

        Permanent vehicle identifier for known vehicles.  # noqa: E501

        :param id_fixed: The id_fixed of this V2XBSM.  # noqa: E501
        :type: str
        """

        self._id_fixed = id_fixed

    @property
    def message_set(self):
        """Gets the message_set of this V2XBSM.  # noqa: E501

        The original format this message was broadcast in before decoding.  # noqa: E501

        :return: The message_set of this V2XBSM.  # noqa: E501
        :rtype: str
        """
        return self._message_set

    @message_set.setter
    def message_set(self, message_set):
        """Sets the message_set of this V2XBSM.

        The original format this message was broadcast in before decoding.  # noqa: E501

        :param message_set: The message_set of this V2XBSM.  # noqa: E501
        :type: str
        """
        allowed_values = ["J2735_200612", "J2735_200911", "J2735_201509", "J2735_201601", "J2735_201603"]  # noqa: E501
        if message_set not in allowed_values:
            raise ValueError(
                "Invalid value for `message_set` ({0}), must be one of {1}"  # noqa: E501
                .format(message_set, allowed_values)
            )

        self._message_set = message_set

    @property
    def vehicle_length(self):
        """Gets the vehicle_length of this V2XBSM.  # noqa: E501

        Vehicle length in Meters  # noqa: E501

        :return: The vehicle_length of this V2XBSM.  # noqa: E501
        :rtype: float
        """
        return self._vehicle_length

    @vehicle_length.setter
    def vehicle_length(self, vehicle_length):
        """Sets the vehicle_length of this V2XBSM.

        Vehicle length in Meters  # noqa: E501

        :param vehicle_length: The vehicle_length of this V2XBSM.  # noqa: E501
        :type: float
        """

        self._vehicle_length = vehicle_length

    @property
    def vehicle_width(self):
        """Gets the vehicle_width of this V2XBSM.  # noqa: E501

        Vehicle width in Meters  # noqa: E501

        :return: The vehicle_width of this V2XBSM.  # noqa: E501
        :rtype: float
        """
        return self._vehicle_width

    @vehicle_width.setter
    def vehicle_width(self, vehicle_width):
        """Sets the vehicle_width of this V2XBSM.

        Vehicle width in Meters  # noqa: E501

        :param vehicle_width: The vehicle_width of this V2XBSM.  # noqa: E501
        :type: float
        """

        self._vehicle_width = vehicle_width

    @property
    def updated(self):
        """Gets the updated of this V2XBSM.  # noqa: E501

        The date time this message was sent via OCTANE.  # noqa: E501

        :return: The updated of this V2XBSM.  # noqa: E501
        :rtype: datetime
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this V2XBSM.

        The date time this message was sent via OCTANE.  # noqa: E501

        :param updated: The updated of this V2XBSM.  # noqa: E501
        :type: datetime
        """

        self._updated = updated

    @property
    def longitude(self):
        """Gets the longitude of this V2XBSM.  # noqa: E501

        Longitude of the transmitting V2X device.  # noqa: E501

        :return: The longitude of this V2XBSM.  # noqa: E501
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this V2XBSM.

        Longitude of the transmitting V2X device.  # noqa: E501

        :param longitude: The longitude of this V2XBSM.  # noqa: E501
        :type: float
        """

        self._longitude = longitude

    @property
    def latitude(self):
        """Gets the latitude of this V2XBSM.  # noqa: E501

        Latitude of the transmitting V2X device.  # noqa: E501

        :return: The latitude of this V2XBSM.  # noqa: E501
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this V2XBSM.

        Latitude of the transmitting V2X device.  # noqa: E501

        :param latitude: The latitude of this V2XBSM.  # noqa: E501
        :type: float
        """

        self._latitude = latitude

    @property
    def elevation(self):
        """Gets the elevation of this V2XBSM.  # noqa: E501

        Elevation of transmitting V2X device. Units in meters  # noqa: E501

        :return: The elevation of this V2XBSM.  # noqa: E501
        :rtype: float
        """
        return self._elevation

    @elevation.setter
    def elevation(self, elevation):
        """Sets the elevation of this V2XBSM.

        Elevation of transmitting V2X device. Units in meters  # noqa: E501

        :param elevation: The elevation of this V2XBSM.  # noqa: E501
        :type: float
        """

        self._elevation = elevation

    @property
    def speed(self):
        """Gets the speed of this V2XBSM.  # noqa: E501

        Reported Velocity of V2X Device. Units in meters/second  # noqa: E501

        :return: The speed of this V2XBSM.  # noqa: E501
        :rtype: float
        """
        return self._speed

    @speed.setter
    def speed(self, speed):
        """Sets the speed of this V2XBSM.

        Reported Velocity of V2X Device. Units in meters/second  # noqa: E501

        :param speed: The speed of this V2XBSM.  # noqa: E501
        :type: float
        """

        self._speed = speed

    @property
    def heading(self):
        """Gets the heading of this V2XBSM.  # noqa: E501

        0 to 359.9875 degrees.  # noqa: E501

        :return: The heading of this V2XBSM.  # noqa: E501
        :rtype: float
        """
        return self._heading

    @heading.setter
    def heading(self, heading):
        """Sets the heading of this V2XBSM.

        0 to 359.9875 degrees.  # noqa: E501

        :param heading: The heading of this V2XBSM.  # noqa: E501
        :type: float
        """

        self._heading = heading

    @property
    def angle(self):
        """Gets the angle of this V2XBSM.  # noqa: E501

        0 to 359.9875 degrees.  # noqa: E501

        :return: The angle of this V2XBSM.  # noqa: E501
        :rtype: float
        """
        return self._angle

    @angle.setter
    def angle(self, angle):
        """Sets the angle of this V2XBSM.

        0 to 359.9875 degrees.  # noqa: E501

        :param angle: The angle of this V2XBSM.  # noqa: E501
        :type: float
        """

        self._angle = angle

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V2XBSM, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2XBSM):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
