# coding: utf-8

"""
    Mcity Control API

    Mcity implementation of OCTANE RESTful/Websocket API designed for autonomous and connected vehicle test facilities/cities.  # noqa: E501

    OpenAPI spec version: 0.0.10
    Contact: mcity-engineering@umich.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class WeatherAlert(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'description': 'str',
        'instruction': 'str',
        'state': 'WeatherAlertState'
    }

    attribute_map = {
        'id': 'id',
        'description': 'description',
        'instruction': 'instruction',
        'state': 'state'
    }

    def __init__(self, id=None, description=None, instruction=None, state=None):  # noqa: E501
        """WeatherAlert - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._description = None
        self._instruction = None
        self._state = None
        self.discriminator = None
        self.id = id
        self.description = description
        self.instruction = instruction
        if state is not None:
            self.state = state

    @property
    def id(self):
        """Gets the id of this WeatherAlert.  # noqa: E501

        An ID number identifying this weather alert  # noqa: E501

        :return: The id of this WeatherAlert.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this WeatherAlert.

        An ID number identifying this weather alert  # noqa: E501

        :param id: The id of this WeatherAlert.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def description(self):
        """Gets the description of this WeatherAlert.  # noqa: E501

        Additional information about the event  # noqa: E501

        :return: The description of this WeatherAlert.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this WeatherAlert.

        Additional information about the event  # noqa: E501

        :param description: The description of this WeatherAlert.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def instruction(self):
        """Gets the instruction of this WeatherAlert.  # noqa: E501

        An advisory message  # noqa: E501

        :return: The instruction of this WeatherAlert.  # noqa: E501
        :rtype: str
        """
        return self._instruction

    @instruction.setter
    def instruction(self, instruction):
        """Sets the instruction of this WeatherAlert.

        An advisory message  # noqa: E501

        :param instruction: The instruction of this WeatherAlert.  # noqa: E501
        :type: str
        """
        if instruction is None:
            raise ValueError("Invalid value for `instruction`, must not be `None`")  # noqa: E501

        self._instruction = instruction

    @property
    def state(self):
        """Gets the state of this WeatherAlert.  # noqa: E501


        :return: The state of this WeatherAlert.  # noqa: E501
        :rtype: WeatherAlertState
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this WeatherAlert.


        :param state: The state of this WeatherAlert.  # noqa: E501
        :type: WeatherAlertState
        """

        self._state = state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WeatherAlert, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WeatherAlert):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
